//CORE_REFERENCE_IMPORTS
//CORE_REFERENCE_IMPORT-patientListService-SSD_SERVICE_ID_sd_VVv6JZ6ue70O2tjZ
import { patientListService as SSD_SERVICE_ID_sd_VVv6JZ6ue70O2tjZ } from './sd-services/patient/patientList/patientListService';
//CORE_REFERENCE_IMPORT-patientListApi-SSD_SERVICE_ID_sd_fg6aLAJPSh1SbdXF
import { patientListApi as SSD_SERVICE_ID_sd_fg6aLAJPSh1SbdXF } from './sd-services/patient/patientList/patientListApi';
//CORE_REFERENCE_IMPORT-idsutil-sd_CBgLAFnpfXPJux1R
import { idsutil as sd_CBgLAFnpfXPJux1R } from './sd-services/idsutil';
//CORE_REFERENCE_IMPORT-ids-sd_9DCUVTdQNHyR9nhR
import { ids as sd_9DCUVTdQNHyR9nhR } from './sd-services/ids';
//CORE_REFERENCE_IMPORT-createAppointmentService-SSD_SERVICE_ID_sd_rBMLYYjvVhOZ76b8
import { createAppointmentService as SSD_SERVICE_ID_sd_rBMLYYjvVhOZ76b8 } from './sd-services/appointments/createAppointment/createAppointmentService';
//CORE_REFERENCE_IMPORT-createAppointmentApi-SSD_SERVICE_ID_sd_nEfu9avH1LHJF46k
import { createAppointmentApi as SSD_SERVICE_ID_sd_nEfu9avH1LHJF46k } from './sd-services/appointments/createAppointment/createAppointmentApi';
//CORE_REFERENCE_IMPORT-doctorFilterService-SSD_SERVICE_ID_sd_F58XlOhAZ8F4OeRg
import { doctorFilterService as SSD_SERVICE_ID_sd_F58XlOhAZ8F4OeRg } from './sd-services/doctor/doctorFilter/doctorFilterService';
//CORE_REFERENCE_IMPORT-doctorFilterApi-SSD_SERVICE_ID_sd_MoSMIyg6HRG1tnOR
import { doctorFilterApi as SSD_SERVICE_ID_sd_MoSMIyg6HRG1tnOR } from './sd-services/doctor/doctorFilter/doctorFilterApi';
//CORE_REFERENCE_IMPORT-doctorService-SSD_SERVICE_ID_sd_lxfVH3wRqGdS2rpQ
import { doctorService as SSD_SERVICE_ID_sd_lxfVH3wRqGdS2rpQ } from './sd-services/doctor/doctorCreation/doctorService';
//CORE_REFERENCE_IMPORT-doctorApi-SSD_SERVICE_ID_sd_toqy16Rh6NHLcttQ
import { doctorApi as SSD_SERVICE_ID_sd_toqy16Rh6NHLcttQ } from './sd-services/doctor/doctorCreation/doctorApi';
//CORE_REFERENCE_IMPORT-departmentService-SSD_SERVICE_ID_sd_I6lm3HkHLDly79aN
import { departmentService as SSD_SERVICE_ID_sd_I6lm3HkHLDly79aN } from './sd-services/department/departmentCreation/departmentService';
//CORE_REFERENCE_IMPORT-departmentApi-SSD_SERVICE_ID_sd_l0HX7iP5IWfzwEkN
import { departmentApi as SSD_SERVICE_ID_sd_l0HX7iP5IWfzwEkN } from './sd-services/department/departmentCreation/departmentApi';
//CORE_REFERENCE_IMPORT-filterDepartmentService-SSD_SERVICE_ID_sd_wodP8aUqBpp4AwbI
import { filterDepartmentService as SSD_SERVICE_ID_sd_wodP8aUqBpp4AwbI } from './sd-services/department/filterDepartment/filterDepartmentService';
//CORE_REFERENCE_IMPORT-filterDepartmentApi-SSD_SERVICE_ID_sd_QJTfXfrbTcP5dtG7
import { filterDepartmentApi as SSD_SERVICE_ID_sd_QJTfXfrbTcP5dtG7 } from './sd-services/department/filterDepartment/filterDepartmentApi';
//CORE_REFERENCE_IMPORT-updateDepartmentService-SSD_SERVICE_ID_sd_CXGNBitJ8i2Oql13
import { updateDepartmentService as SSD_SERVICE_ID_sd_CXGNBitJ8i2Oql13 } from './sd-services/department/updateDepartment/updateDepartmentService';
//CORE_REFERENCE_IMPORT-updateDepartmentApi-SSD_SERVICE_ID_sd_nKaaCzh3n3kJ8sBH
import { updateDepartmentApi as SSD_SERVICE_ID_sd_nKaaCzh3n3kJ8sBH } from './sd-services/department/updateDepartment/updateDepartmentApi';

export const UserRoutes = [
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-patientListService-SSD_SERVICE_ID_sd_VVv6JZ6ue70O2tjZ
SSD_SERVICE_ID_sd_VVv6JZ6ue70O2tjZ,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-patientListApi-SSD_SERVICE_ID_sd_fg6aLAJPSh1SbdXF
SSD_SERVICE_ID_sd_fg6aLAJPSh1SbdXF,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-idsutil-sd_CBgLAFnpfXPJux1R
sd_CBgLAFnpfXPJux1R,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-ids-sd_9DCUVTdQNHyR9nhR
sd_9DCUVTdQNHyR9nhR,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-createAppointmentService-SSD_SERVICE_ID_sd_rBMLYYjvVhOZ76b8
SSD_SERVICE_ID_sd_rBMLYYjvVhOZ76b8,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-createAppointmentApi-SSD_SERVICE_ID_sd_nEfu9avH1LHJF46k
SSD_SERVICE_ID_sd_nEfu9avH1LHJF46k,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-doctorFilterService-SSD_SERVICE_ID_sd_F58XlOhAZ8F4OeRg
SSD_SERVICE_ID_sd_F58XlOhAZ8F4OeRg,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-doctorFilterApi-SSD_SERVICE_ID_sd_MoSMIyg6HRG1tnOR
SSD_SERVICE_ID_sd_MoSMIyg6HRG1tnOR,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-doctorService-SSD_SERVICE_ID_sd_lxfVH3wRqGdS2rpQ
SSD_SERVICE_ID_sd_lxfVH3wRqGdS2rpQ,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-doctorApi-SSD_SERVICE_ID_sd_toqy16Rh6NHLcttQ
SSD_SERVICE_ID_sd_toqy16Rh6NHLcttQ,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-departmentService-SSD_SERVICE_ID_sd_I6lm3HkHLDly79aN
SSD_SERVICE_ID_sd_I6lm3HkHLDly79aN,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-departmentApi-SSD_SERVICE_ID_sd_l0HX7iP5IWfzwEkN
SSD_SERVICE_ID_sd_l0HX7iP5IWfzwEkN,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-filterDepartmentService-SSD_SERVICE_ID_sd_wodP8aUqBpp4AwbI
SSD_SERVICE_ID_sd_wodP8aUqBpp4AwbI,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-filterDepartmentApi-SSD_SERVICE_ID_sd_QJTfXfrbTcP5dtG7
SSD_SERVICE_ID_sd_QJTfXfrbTcP5dtG7,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-updateDepartmentService-SSD_SERVICE_ID_sd_CXGNBitJ8i2Oql13
SSD_SERVICE_ID_sd_CXGNBitJ8i2Oql13,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-updateDepartmentApi-SSD_SERVICE_ID_sd_nKaaCzh3n3kJ8sBH
SSD_SERVICE_ID_sd_nKaaCzh3n3kJ8sBH,
];
